/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_menu_coach (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window_ajout (void);
GtkWidget* create_window_adherent (void);
GtkWidget* create_window_urgence (void);
GtkWidget* create_window3 (void);
